// posts/002-form-abstractions-dx/lab/src/vue/App.vue
<script setup lang="ts">
import { reactive, ref } from 'vue'

type Model = { name: string; email: string; role: string; bio: string; terms: boolean }
const model = reactive<Model>({ name: '', email: '', role: '', bio: '', terms: false })
const errors = reactive<Partial<Record<keyof Model, string>>>({})
const result = ref<Model>()

function submit() {
  errors.name = model.name.trim().length >= 2 ? '' : 'Use pelo menos 2 caracteres.'
  errors.email = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(model.email) ? '' : 'Informe um e-mail válido.'
  errors.role = model.role ? '' : 'Selecione um papel.'
  errors.bio = model.bio.trim().length <= 120 ? '' : 'Use no máximo 120 caracteres.'
  errors.terms = model.terms ? '' : 'Aceite os termos.'
  if (!Object.values(errors).some(Boolean)) result.value = { ...model, name: model.name.trim(), bio: model.bio.trim() }
}
</script>

<template>
  <header class="implementation-header"><span class="badge">Progressive framework</span><h2>Vue</h2><p><code>v-model</code> é nativo; o contrato de validação é da aplicação.</p></header>
  <form @submit.prevent="submit" novalidate>
    <label>Nome<input v-model="model.name" /></label><p class="error">{{ errors.name }}</p>
    <label>E-mail<input v-model="model.email" type="email" /></label><p class="error">{{ errors.email }}</p>
    <label>Papel<select v-model="model.role"><option value="">Selecione</option><option value="dev">Developer</option><option value="lead">Tech Lead</option><option value="manager">Engineering Manager</option></select></label><p class="error">{{ errors.role }}</p>
    <label>Bio<textarea v-model="model.bio" /></label><p class="error">{{ errors.bio }}</p>
    <label class="check"><input v-model="model.terms" type="checkbox" /> Aceito os termos</label><p class="error">{{ errors.terms }}</p>
    <button type="submit">Criar conta</button>
    <pre v-if="result">{{ JSON.stringify(result, null, 2) }}</pre>
  </form>
</template>

// posts/002-form-abstractions-dx/lab/src/react-rhf/App.tsx
import { zodResolver } from '@hookform/resolvers/zod'
import { useState } from 'react'
import { useForm } from 'react-hook-form'
import type { z } from 'zod'
import { markRender } from '../render-meter'
import { accountSchema } from '../react/schema'

type Input = z.input<typeof accountSchema>
type Output = z.output<typeof accountSchema>

export function App() {
  if (import.meta.env.DEV) markRender('App')
  const [result, setResult] = useState<Output>()
  const { register, handleSubmit, formState: { errors } } = useForm<Input, unknown, Output>({
    defaultValues: { name: '', email: '', role: '', bio: '', terms: false },
    resolver: zodResolver(accountSchema),
  })

  return <>
    <header className="implementation-header"><span className="badge">Ecossistema direto</span><h2>React · RHF + Zod</h2><p>As bibliotecas são usadas sem o módulo <code>Field.*</code>.</p></header>
    <form onSubmit={handleSubmit(setResult)} noValidate>
      <label>Nome<input {...register('name')} /></label><p className="error">{errors.name?.message ?? ''}</p>
      <label>E-mail<input {...register('email')} type="email" /></label><p className="error">{errors.email?.message ?? ''}</p>
      <label>Papel<select {...register('role')}><option value="">Selecione</option><option value="dev">Developer</option><option value="lead">Tech Lead</option><option value="manager">Engineering Manager</option></select></label><p className="error">{errors.role?.message ?? ''}</p>
      <label>Bio<textarea {...register('bio')} /></label><p className="error">{errors.bio?.message ?? ''}</p>
      <label className="check"><input {...register('terms')} type="checkbox" /> Aceito os termos</label><p className="error">{errors.terms?.message ?? ''}</p>
      <button type="submit">Criar conta</button>
      {result && <pre>{JSON.stringify(result, null, 2)}</pre>}
    </form>
  </>
}
