// posts/002-form-abstractions-dx/lab/src/vue/App.vue
<script setup lang="ts">
import { reactive, ref } from 'vue'

type Model = { name: string; email: string; role: string; bio: string; terms: boolean }
const model = reactive<Model>({ name: '', email: '', role: '', bio: '', terms: false })
const errors = reactive<Partial<Record<keyof Model, string>>>({})
const result = ref<Model>()

function submit() {
  errors.name = model.name.trim().length >= 2 ? '' : 'Use pelo menos 2 caracteres.'
  errors.email = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(model.email) ? '' : 'Informe um e-mail válido.'
  errors.role = model.role ? '' : 'Selecione um papel.'
  errors.bio = model.bio.trim().length <= 120 ? '' : 'Use no máximo 120 caracteres.'
  errors.terms = model.terms ? '' : 'Aceite os termos.'
  if (!Object.values(errors).some(Boolean)) result.value = { ...model, name: model.name.trim(), bio: model.bio.trim() }
}
</script>

<template>
  <header class="implementation-header"><span class="badge">Progressive framework</span><h2>Vue</h2><p><code>v-model</code> é nativo; o contrato de validação é da aplicação.</p></header>
  <form @submit.prevent="submit" novalidate>
    <label>Nome<input v-model="model.name" /></label><p class="error">{{ errors.name }}</p>
    <label>E-mail<input v-model="model.email" type="email" /></label><p class="error">{{ errors.email }}</p>
    <label>Papel<select v-model="model.role"><option value="">Selecione</option><option value="dev">Developer</option><option value="lead">Tech Lead</option><option value="manager">Engineering Manager</option></select></label><p class="error">{{ errors.role }}</p>
    <label>Bio<textarea v-model="model.bio" /></label><p class="error">{{ errors.bio }}</p>
    <label class="check"><input v-model="model.terms" type="checkbox" /> Aceito os termos</label><p class="error">{{ errors.terms }}</p>
    <button type="submit">Criar conta</button>
    <pre v-if="result">{{ JSON.stringify(result, null, 2) }}</pre>
  </form>
</template>

// posts/002-form-abstractions-dx/lab/src/react-state/App.tsx
import { type FormEvent, useState } from 'react'
import { markRender } from '../render-meter'

type Model = { name: string; email: string; role: string; bio: string; terms: boolean }
type Errors = Partial<Record<keyof Model, string>>
const initialModel: Model = { name: '', email: '', role: '', bio: '', terms: false }

function validate(model: Model): Errors {
  return {
    name: model.name.trim().length >= 2 ? '' : 'Use pelo menos 2 caracteres.',
    email: /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(model.email) ? '' : 'Informe um e-mail válido.',
    role: model.role ? '' : 'Selecione um papel.',
    bio: model.bio.trim().length <= 120 ? '' : 'Use no máximo 120 caracteres.',
    terms: model.terms ? '' : 'Aceite os termos.',
  }
}

export function App() {
  if (import.meta.env.DEV) markRender('App')
  const [model, setModel] = useState(initialModel)
  const [errors, setErrors] = useState<Errors>({})
  const [result, setResult] = useState<Model>()
  const update = <K extends keyof Model>(key: K, value: Model[K]) => setModel(current => ({ ...current, [key]: value }))

  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    const nextErrors = validate(model)
    setErrors(nextErrors)
    if (!Object.values(nextErrors).some(Boolean)) setResult({ ...model, name: model.name.trim(), bio: model.bio.trim() })
  }

  return <>
    <header className="implementation-header"><span className="badge">Somente React</span><h2>React · useState</h2><p>Inputs controlados e validação mantidos pela aplicação.</p></header>
    <form onSubmit={submit} noValidate>
      <label>Nome<input name="name" value={model.name} onChange={event => update('name', event.target.value)} /></label><p className="error">{errors.name ?? ''}</p>
      <label>E-mail<input name="email" value={model.email} onChange={event => update('email', event.target.value)} type="email" /></label><p className="error">{errors.email ?? ''}</p>
      <label>Papel<select name="role" value={model.role} onChange={event => update('role', event.target.value)}><option value="">Selecione</option><option value="dev">Developer</option><option value="lead">Tech Lead</option><option value="manager">Engineering Manager</option></select></label><p className="error">{errors.role ?? ''}</p>
      <label>Bio<textarea name="bio" value={model.bio} onChange={event => update('bio', event.target.value)} /></label><p className="error">{errors.bio ?? ''}</p>
      <label className="check"><input name="terms" checked={model.terms} onChange={event => update('terms', event.target.checked)} type="checkbox" /> Aceito os termos</label><p className="error">{errors.terms ?? ''}</p>
      <button type="submit">Criar conta</button>
      {result && <pre>{JSON.stringify(result, null, 2)}</pre>}
    </form>
  </>
}
